/* Real PDF rendering for the DNO pack — jsPDF, generated on demand from the project.
   Produces the application form, single line diagram, equipment schedule and the
   post-install commissioning docs. Preview opens a blob in a new tab; download saves it. */
import { jsPDF } from 'jspdf'
import { buildSldModel } from './dno'
import type { StudioProject, DnoDoc, DnoApplication } from '../store/types'

const INSTALLER_COMPANY = 'Simplr Solar Ltd'
const MCS_NO = 'MCS-1029384'
const INK = '#12161C'
const MUTE = '#6A7686'
const ACCENT = '#13927B'
const LINE = '#C7CFDA'

type Ctx = { doc: jsPDF; y: number; readonly M: number; readonly W: number }

function newDoc(): Ctx {
  const doc = new jsPDF({ unit: 'mm', format: 'a4' })
  return { doc, y: 20, M: 18, W: 210 }
}
function heading(c: Ctx, kicker: string, title: string, form: string) {
  c.doc.setFillColor(ACCENT); c.doc.rect(0, 0, c.W, 3, 'F')
  c.doc.setTextColor(MUTE); c.doc.setFont('helvetica', 'bold'); c.doc.setFontSize(8)
  c.doc.text(kicker.toUpperCase(), c.M, c.y)
  c.doc.setTextColor(ACCENT); c.doc.text(form, c.W - c.M, c.y, { align: 'right' })
  c.y += 7
  c.doc.setTextColor(INK); c.doc.setFontSize(18); c.doc.text(title, c.M, c.y)
  c.y += 4
  rule(c); c.y += 6
}
function rule(c: Ctx) { c.doc.setDrawColor(LINE); c.doc.setLineWidth(0.3); c.doc.line(c.M, c.y, c.W - c.M, c.y) }
function section(c: Ctx, label: string) {
  ensure(c, 16)
  c.doc.setTextColor(ACCENT); c.doc.setFont('helvetica', 'bold'); c.doc.setFontSize(9)
  c.doc.text(label.toUpperCase(), c.M, c.y); c.y += 5
}
function kv(c: Ctx, rows: [string, string][]) {
  c.doc.setFontSize(10)
  const colW = (c.W - c.M * 2) / 2
  rows.forEach((r, i) => {
    const col = i % 2
    const x = c.M + col * colW
    if (col === 0) ensure(c, 11)
    const yy = c.y
    c.doc.setTextColor(MUTE); c.doc.setFont('helvetica', 'normal'); c.doc.setFontSize(8)
    c.doc.text(r[0].toUpperCase(), x, yy)
    c.doc.setTextColor(INK); c.doc.setFont('helvetica', 'bold'); c.doc.setFontSize(10.5)
    c.doc.text(r[1] || '—', x, yy + 5)
    if (col === 1 || i === rows.length - 1) c.y += 12
  })
}
function paragraph(c: Ctx, text: string) {
  ensure(c, 16)
  c.doc.setTextColor(INK); c.doc.setFont('helvetica', 'normal'); c.doc.setFontSize(10)
  const lines = c.doc.splitTextToSize(text, c.W - c.M * 2)
  c.doc.text(lines, c.M, c.y); c.y += lines.length * 5 + 3
}
function ensure(c: Ctx, need: number) { if (c.y + need > 282) { c.doc.addPage(); c.y = 20 } }
function footer(c: Ctx) {
  const n = c.doc.getNumberOfPages()
  for (let i = 1; i <= n; i++) {
    c.doc.setPage(i)
    c.doc.setDrawColor(LINE); c.doc.setLineWidth(0.3); c.doc.line(c.M, 288, c.W - c.M, 288)
    c.doc.setTextColor(MUTE); c.doc.setFont('helvetica', 'normal'); c.doc.setFontSize(7.5)
    c.doc.text(`${INSTALLER_COMPANY} · ${MCS_NO} · Generated by Simplr Studio DNO Autopilot`, c.M, 292)
    c.doc.text(`Page ${i} of ${n}`, c.W - c.M, 292, { align: 'right' })
  }
}

function table(c: Ctx, cols: { header: string; w: number; align?: 'right' }[], rows: string[][]) {
  const startX = c.M
  ensure(c, 10)
  c.doc.setFillColor('#F1F4F9'); c.doc.rect(startX, c.y - 4, c.W - c.M * 2, 7, 'F')
  c.doc.setTextColor(MUTE); c.doc.setFont('helvetica', 'bold'); c.doc.setFontSize(8)
  let x = startX
  cols.forEach((col) => { c.doc.text(col.header.toUpperCase(), col.align === 'right' ? x + col.w - 1 : x + 1, c.y, { align: col.align }); x += col.w })
  c.y += 5
  c.doc.setFont('helvetica', 'normal'); c.doc.setFontSize(9.5)
  rows.forEach((row) => {
    ensure(c, 8); x = startX
    c.doc.setDrawColor('#E7ECF2'); c.doc.line(startX, c.y - 3.5, c.W - c.M, c.y - 3.5)
    row.forEach((cell, ci) => {
      const col = cols[ci]
      c.doc.setTextColor(ci === 0 ? INK : MUTE)
      const lines = c.doc.splitTextToSize(cell, col.w - 2)
      c.doc.text(lines, col.align === 'right' ? x + col.w - 1 : x + 1, c.y, { align: col.align })
      x += col.w
    })
    c.y += 6
  })
  c.y += 2
}

function drawSld(c: Ctx, app: DnoApplication) {
  const nodes = buildSldModel(app)
  const cx = c.M + 22
  const boxW = 30, boxH = 11, gap = 8
  nodes.forEach((n, i) => {
    ensure(c, boxH + gap + 4)
    const top = c.y
    c.doc.setDrawColor(ACCENT); c.doc.setLineWidth(0.4)
    c.doc.setFillColor('#F5F7FA'); c.doc.roundedRect(cx - boxW / 2, top, boxW, boxH, 1.5, 1.5, 'FD')
    c.doc.setTextColor(INK); c.doc.setFont('helvetica', 'bold'); c.doc.setFontSize(8)
    c.doc.text(String(i + 1), cx, top + 7, { align: 'center' })
    c.doc.setTextColor(INK); c.doc.setFont('helvetica', 'bold'); c.doc.setFontSize(10)
    c.doc.text(n.label, cx + boxW / 2 + 6, top + 5)
    if (n.note) { c.doc.setTextColor(MUTE); c.doc.setFont('helvetica', 'normal'); c.doc.setFontSize(8); c.doc.text(n.note, cx + boxW / 2 + 6, top + 9.5) }
    if (i < nodes.length - 1) { c.doc.setDrawColor(LINE); c.doc.setLineWidth(0.5); c.doc.line(cx, top + boxH, cx, top + boxH + gap) }
    c.y = top + boxH + gap
  })
}

// ── Document builders keyed off the doc name/kind ────────────────────────────
function buildApplicationPdf(c: Ctx, p: StudioProject, app: DnoApplication) {
  heading(c, 'Distribution Network Operator application', `${p.address}`, app.form)
  section(c, 'Classification')
  paragraph(c, `${app.classification} — ${app.rationale}`)
  kv(c, [
    ['Connection form', app.form],
    ['Aggregate rated current', `${app.aggregateRcA} A / phase`],
    ['Meets SGI criteria', app.meetsSgi ? 'Yes' : 'No'],
    ['Supply phase', app.phase === 1 ? 'Single phase' : 'Three phase'],
  ])
  section(c, 'Site & connection')
  kv(c, [
    ['Customer', p.customer],
    ['Site address', p.address],
    ['MPAN', app.mpan ?? '—'],
    ['DNO', app.dnoRegion],
    ['Install location', app.installLocation ?? '—'],
    ['Lockable isolator', app.isolatorLocation ?? '—'],
    ['Pre-existing generation', app.preExisting ? 'Yes' : 'No'],
    ['Export limitation', app.exportScheme && app.exportScheme !== 'none' ? `${app.exportScheme} · ${app.exportLimitKw ?? '?'} kW` : 'Not limited'],
  ])
  section(c, 'Generation & storage')
  table(c, [{ header: 'Equipment', w: 78 }, { header: 'Type', w: 30 }, { header: 'Rating', w: 26, align: 'right' }, { header: 'ENA ref', w: 40, align: 'right' }],
    app.devices.map((d) => [`${d.make} ${d.model}`, d.kind, `${d.capacityKw} ${d.kind === 'battery' ? 'kWh' : 'kW'}`, d.typeTestRef ?? 'not listed']))
  section(c, 'Installer')
  kv(c, [['Company', INSTALLER_COMPANY], ['MCS certificate', MCS_NO], ['Engineer', p.owner], ['Reference', app.reference ?? 'pending']])
  // Declaration + signatures
  c.doc.addPage(); c.y = 20
  heading(c, 'Declaration', 'Installer & customer declaration', app.form)
  paragraph(c, 'We confirm the information in this application is correct and that the installation complies with the Distribution Code, the relevant Engineering Recommendation (G98/G99) and BS 7671. The equipment listed is type-tested and registered where required.')
  c.y += 6
  signatureRow(c, 'Installer', app.signatures.installer?.by ?? p.owner, app.signatures.installer?.signedAt)
  signatureRow(c, 'Customer', app.signatures.client?.by ?? p.customer, app.signatures.client?.signedAt)
}

function signatureRow(c: Ctx, role: string, name: string, at?: string) {
  ensure(c, 26)
  c.doc.setTextColor(MUTE); c.doc.setFont('helvetica', 'bold'); c.doc.setFontSize(8); c.doc.text(role.toUpperCase(), c.M, c.y)
  c.y += 12
  c.doc.setDrawColor(LINE); c.doc.setLineWidth(0.3); c.doc.line(c.M, c.y, c.M + 80, c.y)
  c.doc.setTextColor(INK); c.doc.setFont('helvetica', 'italic'); c.doc.setFontSize(13); c.doc.text(at ? name : '', c.M + 4, c.y - 2)
  c.doc.setFont('helvetica', 'normal'); c.doc.setFontSize(9); c.doc.setTextColor(MUTE)
  c.doc.text(`${name}${at ? `   ·   Signed ${at}` : '   ·   Awaiting signature'}`, c.M, c.y + 5)
  c.y += 16
}

function buildSldPdf(c: Ctx, p: StudioProject, app: DnoApplication) {
  heading(c, 'Single line diagram', p.address, app.form)
  const kwp = app.strings.reduce((s, st) => s + (st.panels * st.watts) / 1000, 0)
  paragraph(c, `${Math.round(kwp * 100) / 100} kWp array · ${app.strings.length} string(s) · ${app.phase === 1 ? 'single' : 'three'}-phase connection at MPAN ${app.mpan ?? '—'}.`)
  c.y += 2
  drawSld(c, app)
}

function buildEquipmentPdf(c: Ctx, p: StudioProject, app: DnoApplication) {
  heading(c, 'Equipment schedule', p.address, app.form)
  paragraph(c, 'Every generating and storage device on this installation, matched to its ENA type-test / EREC register reference. Any device not on the register is flagged for manual evidence.')
  table(c, [{ header: 'Make & model', w: 74 }, { header: 'Type', w: 26 }, { header: 'Rating', w: 24, align: 'right' }, { header: 'ENA type-test ref', w: 50, align: 'right' }],
    app.devices.map((d) => [`${d.make} ${d.model}`, d.kind, `${d.capacityKw} ${d.kind === 'battery' ? 'kWh' : 'kW'}`, d.typeTestRef ?? 'NOT LISTED']))
  const off = app.devices.filter((d) => !d.onRegister).length
  paragraph(c, off ? `⚠ ${off} device(s) are not on the ENA register — attach manufacturer type-test evidence before submission.` : 'All devices are on the ENA register.')
}

function buildPostInstallPdf(c: Ctx, p: StudioProject, app: DnoApplication, doc: DnoDoc) {
  const commissioning = /Commissioning/i.test(doc.name)
  heading(c, commissioning ? 'Commissioning certificate' : 'Installation confirmation', p.address, app.form)
  kv(c, [
    ['DNO reference', app.reference ?? '—'],
    ['DNO', app.dnoRegion],
    ['Installed date', app.actualInstallDate ?? '—'],
    ['System size', p.systemKwp ? `${p.systemKwp} kWp` : '—'],
    ['Total output', `${app.devices.filter((d) => d.kind === 'inverter').reduce((s, d) => s + d.capacityKw, 0)} kW`],
    ['MPAN', app.mpan ?? '—'],
  ])
  paragraph(c, commissioning
    ? 'The installation has been commissioned and tested in accordance with the relevant Engineering Recommendation and BS 7671. Protection settings have been verified against the DNO connection agreement.'
    : 'This confirms the installation described above has been completed and energised under the terms of the DNO connection agreement. This notice is submitted to close out the application.')
  c.y += 4
  signatureRow(c, 'Commissioning engineer', app.signatures.installer?.by ?? p.owner, app.actualInstallDate ?? app.signatures.installer?.signedAt)
}

function build(p: StudioProject, docMeta: DnoDoc): jsPDF {
  const c = newDoc()
  const app = p.dno!
  const name = docMeta.name
  if (docMeta.kind === 'post-install') buildPostInstallPdf(c, p, app, docMeta)
  else if (/SingleLineDiagram/i.test(name)) buildSldPdf(c, p, app)
  else if (/EquipmentSchedule/i.test(name)) buildEquipmentPdf(c, p, app)
  else buildApplicationPdf(c, p, app)
  footer(c)
  return c.doc
}

export function openDnoPdf(p: StudioProject, docMeta: DnoDoc) {
  if (!p.dno) return
  const url = build(p, docMeta).output('bloburl')
  window.open(url, '_blank', 'noopener')
}
export function downloadDnoPdf(p: StudioProject, docMeta: DnoDoc) {
  if (!p.dno) return
  build(p, docMeta).save(docMeta.name)
}
